"""create outbound tables

Revision ID: 003a3ca7193f
Revises: bb81601b41f6
Create Date: 2026-07-24 11:30:30.232706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003a3ca7193f'
down_revision: Union[str, Sequence[str], None] = 'bb81601b41f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_type', sa.String(length=50), nullable=False),
    sa.Column('work_order_number', sa.String(length=100), nullable=True),
    sa.Column('sales_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outbound_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['outbound_id'], ['outbounds.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_purchase_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outbound_item_id', sa.Integer(), nullable=False),
    sa.Column('purchase_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outbound_item_id'], ['outbound_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_purchase_allocations')
    op.drop_table('outbound_items')
    op.drop_table('outbounds')
    # ### end Alembic commands ###
