"""add outbound transfer allocations

Revision ID: 06f4c384837f
Revises: 68c0a3c4b425
Create Date: 2026-08-05 10:57:43.379720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f4c384837f'
down_revision: Union[str, Sequence[str], None] = '68c0a3c4b425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_transfer_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outbound_item_id', sa.Integer(), nullable=False),
    sa.Column('transfer_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outbound_item_id'], ['outbound_items.id'], ),
    sa.ForeignKeyConstraint(['transfer_item_id'], ['transfer_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_transfer_allocations')
    # ### end Alembic commands ###
